### ISSUE TITLE
iso codes with local (expl. en-us, zh-cn, zh-tw)

### ISSUE THREAD

**Issue by Weedshaker** [danieledesantis/jquery-language-detection#2]
Hi,

first, great plugin! Thanks a lot!

Though, I ran in a little issue with having traditional and simplified Chinese on my page. They couldn't be distinguished (were both "zh") due to line 40:

`if(languages[i]['code']==lang.substr(0,2)) {`

I replaced it with:

`if(languages[i]['code']===lang){`

I kinda had to use "===" not that it may matches "en-us" with "en-US" and later returns undefined, if the page doesn't properly uses upper and lower cases. Note that the browser delivers the navigator language as for example "en-US". But I don't know how consistent this is, so I made all language codes lower case on the site and changed the line 34:

`methods.setLanguage(options.domain, options.useFullPaths, options.languages, options.expires, language);`

to

`methods.setLanguage(options.domain, options.useFullPaths, options.languages, options.expires, language.toLowerCase());`

this solved all my issues.

Greetz

PS: this maybe is helpful for people wanna read out the options instead of defining everything again after defining it in their language menu html:

``` javascript
let languages = [];
$('.languageDropDown').siblings('ul.dropdown-menu').find('li a').each(function(e){
    languages.push({
        code: $(this).data('language'),
        path: $(this).attr('href'),
        defaultLanguage: $(this).data('language') === 'en-us'
    });
});
$(document).languageDetection({
    languages: languages
});
```

**Comment by danieledesantis** [comment]
Hi,
thanks for your help!
I'll find a fix for the reported issue

And thanks for the useful snippet for the options!

Best,
Daniele
