### ISSUE TITLE
redirect loop to second language

### ISSUE THREAD

**Issue by verymilan** [danieledesantis/jquery-language-detection#3]
Hi there, turns our you promising script loops to the second, none-default language.

```
$(document).ready(function(){$(document).languageDetection({domain:'http://localhost:1313/',languages:[{code:'en',path:'home',defaultLanguage:true},{code:'pl',path:'pl/dom'}],expires:10})});
```
jQuery v2.2.3

**Comment by danieledesantis** [comment]
Hi, seems like a cookie issue. Have you checked if cookies are set properly?

**Comment by verymilan** [comment]
Hmm i disabled all restrictions in chromium so far without success.
A LanguageDetection cookie is set:

![2016-11-10-203621_1920x1200_scrot](https://cloud.githubusercontent.com/assets/10698140/20191376/808f576a-a785-11e6-8e08-75efc3545788.png)

Epiphany brings me to /home as wanted but is falling into the loop as soon as i change the locale to pl.
After that it stays in the loop also when i try to open /home again.

Vivaldi is the same as Chromium.

Firefox does it as Epiphany - there is no cookie set until i switch to the pl locale manuelly:

```
                <li><a class="language" data-language="en">English</a></li>
                <li><a class="language" data-language="pl">Polski</a></li>
```

**Comment by danieledesantis** [comment]
This is correct, the cookie is set only when you click on the link.
Did you set the lang="pl" attribute in the<html> tag of the Polish page?
Without that, the plugin starts looping, because that's what the script looks for to detect wheter you're in the right page.

**Comment by verymilan** [comment]
Ah, this might be a misunderstanding by me. 
I generate pages using Hugo while the loop happens, the language tag is empty where it should be at least en. 

I will give feedback asap.

**Comment by verymilan** [comment]
Okey, sorry for wasting you time - the lang tag is now set properbly and the loop is away. :)

**Comment by danieledesantis** [comment]
No problem! Glad to know you got it sorted :)
